# Generated by Django 5.2.6 on 2025-09-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
